name: health_care_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  location: ^5.0.3
  http: ^1.1.0
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  animated_toggle_switch: ^0.6.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  flutter_local_notifications: ^16.1.0
  dropdown_button2: ^2.3.9
  cloud_firestore: ^4.15.10
  flutter_slidable: ^3.1.0
  motion_toast: ^2.9.0
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_splash.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"
    image: assets/logo_splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Italic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: fonts/Poppins-Black.ttf
        weight: 900
      - asset: fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic