name: health_care_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Italic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: fonts/Poppins-Black.ttf
        weight: 900
      - asset: fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic