// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYG_gbBz8OtmwyzU5ZBY4jZQ8ZOkHdNM',
    appId: '1:931934117255:web:d041467b44bb961c2b8722',
    messagingSenderId: '931934117255',
    projectId: 'healthapp-fc7fb',
    authDomain: 'healthapp-fc7fb.firebaseapp.com',
    storageBucket: 'healthapp-fc7fb.appspot.com',
    measurementId: 'G-PLBFSVWV1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPyZ7MEd4quqJ3R73HYxNc6WWx1W_CmM',
    appId: '1:931934117255:android:1110bfa1c25214b72b8722',
    messagingSenderId: '931934117255',
    projectId: 'healthapp-fc7fb',
    storageBucket: 'healthapp-fc7fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1_52y41H60TYiJHid2pUwb4Pp9qYRBd8',
    appId: '1:931934117255:ios:4f614813336152492b8722',
    messagingSenderId: '931934117255',
    projectId: 'healthapp-fc7fb',
    storageBucket: 'healthapp-fc7fb.appspot.com',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1_52y41H60TYiJHid2pUwb4Pp9qYRBd8',
    appId: '1:931934117255:ios:5453cae2bbfb18e32b8722',
    messagingSenderId: '931934117255',
    projectId: 'healthapp-fc7fb',
    storageBucket: 'healthapp-fc7fb.appspot.com',
    iosBundleId: 'com.example.healthCareApp.RunnerTests',
  );
}
